/**
 * Actual Bravura 1.392 outlines from VexFlow 5.0.0's bundled WOFF2.
 * Generated by scripts/generate-bravura-icons.py; do not edit paths by hand.
 * Source WOFF2 SHA-256: 5c25278c208ca455dc7c3c0c95d833e134aca6d740a023767af50d0dfa06ef82
 * Copyright (c) 2021, Steinberg Media Technologies GmbH.
 * SIL Open Font License 1.1; see THIRD_PARTY_NOTICES.md.
 *
 * Each export is independent and needs no font loading or runtime geometry.
 * Original outline coordinates are preserved with SVG's y direction.
 * Compact SVG commands preserve every endpoint and control point exactly.
 * Each viewBox centers actual ink, fits it to 20/24 of the icon box, and
 * caps nominal size at 40px so small marks such as dots stay proportional.
 */
import type { IconDefinition } from '../icon-definition.js';

/** Bravura noteDoubleWhole, SMuFL U+E1D0. */
export const bravuraNoteDoubleWhole: IconDefinition = {
  name: 'music:noteDoubleWhole',
  viewBox: '-65.5 -394 786 786',
  paths: ['M34 161V-162q0-3-3-6-2-2-7-2H10q-5 0-7 2-3 3-3 6V161q0 3 3 5q2 2 7 2H24q5 0 7-2q3-2 3-5Zm63 0V-162q0-3-3-6-3-2-7-2H73q-5 0-7 2-3 3-3 6V161q0 3 3 5q2 2 7 2H87q4 0 7-2t3-5Zm495 0V-162q0-3-3-6-3-2-7-2H567q-4 0-7 2-3 3-3 6V161q0 3 3 5t7 2h15q4 0 7-2t3-5Zm63 0V-162q0-3-3-6-3-2-8-2H630q-4 0-7 2-4 3-4 6V161q0 3 4 5q3 2 7 2h14q5 0 8-2t3-5ZM332-137q-109 1-171 40Q99-59 98-1q-1 55 51 95t172 42q132-2 184-40q53-39 51-97-4-60-74-97-69-38-150-39ZM218-69q10-27 35-35q24-8 51-7q57 3 95 48t39 97q-1 40-23 59-22 18-59 18-33-1-58-17-26-16-46-40-15-20-26-46-11-25-11-52q0-13 3-25Z'],
};

/** Bravura noteWhole, SMuFL U+E1D2. */
export const bravuraNoteWhole: IconDefinition = {
  name: 'music:noteWhole',
  viewBox: '-70.4731 -299.5 600 600',
  paths: ['M235-136Q125-135 63-96Q1-58 0-1T51 95q53 40 173 42q132-2 184-41q53-39 51-97-5-59-74-96-70-38-150-39Zm-28 25q57 3 95 48q38 46 39 98-1 41-23 59-23 18-60 18-56-3-97-50-42-48-44-103q1-41 26-56t64-14Z'],
};

/** Bravura noteHalfUp, SMuFL U+E1D3. */
export const bravuraNoteHalfUp: IconDefinition = {
  name: 'music:noteHalfUp',
  viewBox: '-441.3809 -977 1224 1224',
  paths: ['M112 145q139-8 186-82q47-73 43-111V-875H311v757q-15-13-36-20-22-7-48-7Q99-139 49-71-2-3 0 49q1 46 32 71q32 25 80 25ZM256-97q19 0 34 13q14 13 15 33q1 17-22 41T200 53q-39 26-67 37-27 10-46 10-21 0-37-14Q35 72 34 51q9-47 90-95q82-49 132-53Z'],
};

/** Bravura noteQuarterUp, SMuFL U+E1D5. */
export const bravuraNoteQuarterUp: IconDefinition = {
  name: 'music:noteQuarterUp',
  viewBox: '-443.6 -976.6 1219.2 1219.2',
  paths: ['M302-115q-14-13-35-19-20-7-45-7-95 3-157 58Q2-28 0 47q1 45 32 69q30 25 77 25q80-3 149-58q69-56 74-130V-875H302Z'],
};

/** Bravura note8thUp, SMuFL U+E1D7. */
export const bravuraNote8thUp: IconDefinition = {
  name: 'music:note8thUp',
  viewBox: '-323.6 -974.1 1213.2 1213.2',
  paths: ['M451-594q-39-59-68-122-28-63-41-135-2-12-9-17t-21-5q-4 0-6 2-3 2-4 7v746q-14-13-35-19-20-7-45-7-95 3-157 58Q2-31 0 44q1 45 32 69q30 25 77 25q80-3 149-58q69-56 74-130V-611q48 32 95 97q47 66 72 124q11 26 18 66q6 39 6 84q0 34-6 68-5 35-18 69-3 9-3 15q0 12 6 19q5 7 10 10l2 1q7 1 15-3q7-5 11-17q2-4 13-57q11-54 13-116-1-94-34-181-32-87-81-162Z'],
};

/** Bravura note16thUp, SMuFL U+E1D9. */
export const bravuraNote16thUp: IconDefinition = {
  name: 'music:note16thUp',
  viewBox: '-316.1 -974.1 1213.2 1213.2',
  paths: ['M552-327q0-2 0-4-1-2-1-5t1-7q4-6 14-43t11-84q0-10-1-18q0-9-2-18-7-48-31-83t-77-91q-42-39-77-72-36-33-50-108-2-8-8-11-7-2-12-2t-11 0q-5 1-6 1v754q-14-13-35-19-20-7-45-7-95 3-157 58Q2-31 0 44q1 45 32 69q30 25 77 25q80-3 149-58q69-56 74-130V-474q42 0 87 27t90 116q17 36 25 73q7 37 7 76q0 44-8 89-1 3-1 5t0 4q0 10 6 18q5 8 16 8q5 0 10-4q5-3 10-13q3-6 5-39t2-71v-22q0-32-8-62-7-30-21-58ZM538-440q-1 6-2 13t-5 13q-1 2-5 4t-8 2-7-4q-12-18-25-35-13-16-29-34-36-38-67-70-30-31-47-90-1-2-1-3q0-3 4-7q4-3 10-3h8q46 2 85 34q38 32 63 71q14 20 20 42q7 23 7 47q0 5 0 10t-1 10Z'],
};

/** Bravura note32ndUp, SMuFL U+E1DB. */
export const bravuraNote32ndUp: IconDefinition = {
  name: 'music:note32ndUp',
  viewBox: '-415.1 -1139.1 1393.2 1393.2',
  paths: ['M536-314q-1-3-1-7q0-3 1-6q3-7 12-41q10-34 11-78q0-24-5-48-5-23-16-45q7-20 13-48q7-28 7-58q0-7 0-14-1-7-2-14-7-43-29-76-23-33-72-85-39-37-73-68t-48-102q-1-7-8-13t-12-6q-5 1-8 6-4 5-4 6v893q-15-13-35-19-21-7-45-7-95 3-157 58Q2-31 0 44q1 45 32 69q30 25 77 25q79-3 148-58q69-56 74-130V-450q39 0 81 26t83 107q16 33 24 67q7 34 7 70q0 42-8 85q0 2 0 4-1 2-1 3q0 9 4 15q4 7 9 9q3 2 6 2q9 0 20-16q2-6 5-34q2-27 2-61q0-36-6-72-7-35-21-69ZM522-624q-2 8-5 19-3 12-7 25-10-13-24-28t-31-34q-38-37-69-68-32-31-45-100q42-1 85 24t84 93q8 15 12 27q3 11 3 21q0 6-1 11t-2 10Zm-1 206q-1 6-2 12t-3 11q-1 2-4 4t-7 2q-2 0-4-1t-3-3q-11-16-22-30t-24-29l-5-5q-33-36-62-65t-45-84q0-1 4-7q4-5 9-6q63 3 115 58t55 119q0 12-2 24Z'],
};

/** Bravura note64thUp, SMuFL U+E1DD. */
export const bravuraNote64thUp: IconDefinition = {
  name: 'music:note64thUp',
  viewBox: '-534.5 -1358 1632 1632',
  paths: ['M536-315q-1-3-1-7q0-3 1-6q3-7 12-41q10-34 11-78q0-24-5-48-5-23-16-45q7-20 13-48q7-28 7-58q0-23-5-45-6-23-17-43q7-19 14-49t8-62q0-14-2-27-7-43-29-76-23-33-72-85-39-37-73-68t-48-102q-1-7-8-13t-12-6q-5 1-8 6-4 5-4 6V-118q-15-13-35-19-21-7-45-7-95 3-157 58Q2-31 0 44q1 45 32 69q30 25 77 25q79-3 148-58q69-56 74-130V-451q39 0 81 26t83 107q16 33 24 67q7 34 7 70q0 42-8 85q0 2 0 4-1 2-1 3q0 9 4 15q4 7 9 9q3 2 6 2q9 0 20-16q2-6 5-34q2-27 2-61q0-36-6-72-7-35-21-69ZM522-823l-13 49q-10-13-24-28-13-14-30-33-38-37-69-68-30-31-44-102q0-1 0-2t-1-2q43-1 85 24q43 25 84 93q8 15 12 27q3 11 3 21q0 6-1 11t-2 10Zm0 198q-2 8-5 19-3 12-7 25-10-13-24-28t-31-34q-38-37-69-68-32-31-45-100q42-1 85 24t84 93q8 15 12 27q3 11 3 21q0 6-1 11t-2 10Zm-1 206q-1 6-2 12t-3 11q-1 2-4 4t-7 2q-2 0-4-1t-3-3q-11-16-22-30t-24-29l-5-5q-33-36-62-65t-45-84q0-1 4-7q4-5 9-6q63 3 115 58t55 119q0 12-2 24Z'],
};

/** Bravura note128thUp, SMuFL U+E1DF. */
export const bravuraNote128thUp: IconDefinition = {
  name: 'music:note128thUp',
  viewBox: '-646.1 -1562.6 1855.2 1855.2',
  paths: ['M536-315q-1-3-1-7q0-3 1-6q3-7 12-41q10-34 11-78q0-24-5-48-5-23-16-45q7-20 13-48q7-28 7-58q0-23-5-45-6-23-17-43q7-19 14-49t8-62q0-14-2-27-3-16-7-29t-10-26q7-19 13-46t6-56q0-8 0-15-1-7-2-14-7-43-29-76-23-33-72-85-39-37-73-68t-48-102q-1-7-8-13t-12-6q-5 1-8 6-4 5-4 6V-118q-14-13-35-19-20-7-45-7-95 3-157 58Q2-31 0 44q1 45 32 69q30 25 77 25q80-3 149-58q69-56 74-130V-451q39 1 80 26q42 26 83 107q16 33 24 67q7 34 7 70q0 42-8 85q0 2 0 4-1 2-1 3q0 9 4 15q4 7 9 9q3 2 6 2q9 0 20-16q2-6 5-34q2-27 2-61q0-36-6-72-7-35-21-69Zm-14-694q-2 7-4 17-3 11-7 23-10-13-24-29t-32-35q-37-36-69-66t-46-96q42-1 85 24t85 93q8 15 12 27q3 11 3 21q0 6-1 11t-2 10Zm0 186l-13 49q-10-13-24-28-13-14-30-33-38-37-69-68t-45-102q0-1 0-2t-1-2q43-1 86 24t84 93q8 15 12 27q3 11 3 21q0 6-1 11t-2 10Zm0 198q-2 8-5 19-3 12-7 25-10-13-24-28t-31-34q-38-37-69-68-32-31-45-100q42-1 85 24t84 93q8 15 12 27q3 11 3 21q0 6-1 11t-2 10Zm-1 206q-1 6-2 12t-3 11q-1 2-4 4t-7 2q-2 0-4-1t-3-3q-11-16-22-30t-24-29l-5-5q-33-36-62-65t-45-84q0-1 4-7q4-5 9-6q63 3 115 58t55 119q0 12-2 24Z'],
};

/** Bravura restDoubleWhole, SMuFL U+E4E2. */
export const bravuraRestDoubleWhole: IconDefinition = {
  name: 'music:restDoubleWhole',
  viewBox: '-237.5 -425 600 600',
  paths: ['M125-15V-235q0-6-5-11-4-4-12-4H16q-7 0-11 4-5 5-5 11V-15Q0-9 5-5Q9 0 16 0h92q8 0 12-5q5-4 5-10Z'],
};

/** Bravura restWhole, SMuFL U+E4E3. */
export const bravuraRestWhole: IconDefinition = {
  name: 'music:restWhole',
  viewBox: '-159 -237 600 600',
  paths: ['M282 109V17q0-11-8-19-7-7-18-7H26Q15-9 7-2Q0 6 0 17v92q0 11 7 18q8 8 19 8H256q11 0 18-8q8-7 8-18Z'],
};

/** Bravura restHalf, SMuFL U+E4E4. */
export const bravuraRestHalf: IconDefinition = {
  name: 'music:restHalf',
  viewBox: '-159 -370 600 600',
  paths: ['M282-24v-92q0-11-8-19-7-7-18-7H26q-11 0-19 7-7 8-7 19v92Q0-13 7-6q8 8 19 8H256q11 0 18-8q8-7 8-18Z'],
};

/** Bravura restQuarter, SMuFL U+E4E5. */
export const bravuraRestQuarter: IconDefinition = {
  name: 'music:restQuarter',
  viewBox: '-313.3 -447.8 897.6 897.6',
  paths: ['M78 38q12 15 23 30q10 14 20 30q2 3 4 8q2 4 2 6q0 1 0 2t-1 2q-2 3-4 4-3 1-7 1-3 0-8-1t-8-2q-2 0-4 0l-8-3q-39 1-62 30Q2 173 1 211q0 37 31 75q30 38 85 80q6 4 13 7q7 2 13 2q5 0 10-2q4-1 5-4q2-4 2-7q0-7-5-13t-11-11q-10-1-17-15-7-13-9-21-4-12-4-26q0-31 16-52q16-20 47-21q22 0 44 6t35 11l1 1q3 1 5 1t3 0q5 0 5-4-1-10-14-29-13-18-23-28-29-34-49-66-19-32-20-73q0-2 0-3l1-7q0-2 0-3q4-43 25-80q20-36 41-67q4-8 4-15q0-8-2-13-2-6-2-6-9-10-76-90-68-80-89-103-4-4-9-6-4-2-9-2-8 0-14 5t-6 16q0 7 4 16q6 9 32 44t29 90q0 28-13 60-14 32-47 67-7 8-11 15-3 8-3 14q1 11 5 17q4 7 5 7Z'],
};

/** Bravura rest8th, SMuFL U+E4E6. */
export const bravuraRest8th: IconDefinition = {
  name: 'music:rest8th',
  viewBox: '-176.5 -261.5 600 600',
  paths: ['M134-107q-1-28-20-47T67-174q-28 1-47 20T0-107Q0-91 8-78q7 13 19 22q12 8 26 13q14 4 28 4q11 0 21-2t18-5q10-3 18-6q9-4 18-9q3-1 5-1q3 0 4 3q1 2 1 6q0 5-1 11-6 21-41 121T72 238q1 9 12 11t17 2q8 0 18-2q9-2 17-8q8-23 52-177q43-154 49-176q3-14 6-24q3-11 4-15-1-7-5-11-5-4-7-5-1 0-4 0-3 1-7 4-7 8-35 35T134-97Z'],
};

/** Bravura rest16th, SMuFL U+E4E7. */
export const bravuraRest16th: IconDefinition = {
  name: 'music:rest16th',
  viewBox: '-247.4 -246.9 814.8 814.8',
  paths: ['M208-111q-1-29-20-48t-48-20q-29 1-48 20T72-111q1 31 26 49q24 19 54 19q20 0 41-6q20-6 37-16q4-2 7-2q5 0 5 7-3 20-26 90-24 70-32 90-7 14-22 23-15 8-27 8q1-6 1-10-1-29-20-48T68 73Q39 74 20 93T0 141q1 31 26 49q24 19 54 19q20 0 39-6t36-15q4 0 4 6l-1 1q0 1 0 1L63 479q0 0 0 1l-1 1q0 7 7 13q8 6 24 6q21 0 28-7q8-7 10-16L247 96q20-65 32-108q13-42 13-44q2-5 13-46q11-40 14-55q0-1 1-2q0-1 0-2q0-5-4-7-4-3-6-4-4 0-6 1-3 1-5 3-7 8-35 35-29 28-56 32Z'],
};

/** Bravura rest32nd, SMuFL U+E4E8. */
export const bravuraRest32nd: IconDefinition = {
  name: 'music:rest32nd',
  viewBox: '-374.1 -518.6 1111.2 1111.2',
  paths: ['M353-419q-4 0-6 1-3 1-5 3-7 7-35 35-29 27-56 31v-9q-1-29-20-48t-48-20q-29 1-48 20t-20 48q0 15 8 28t20 22q6 5 13 8q7 4 15 6q6 2 12 3q7 1 14 1q20 0 39-7q20-6 37-15q1-1 2-1t2 0q5 0 8 6q3 5 3 11l-1 2q0 0 0 1L248-133q-5 13-23 24T194-97q1-5 1-9-1-29-20-48t-48-20q-29 1-48 20T59-106q0 15 8 28T87-56q12 10 27 14q12 3 27 4q20 0 39-7q19-6 36-15q2-1 3-1q4 0 5 5q2 4 2 8L186 116q-5 16-22 25-16 9-29 10q1-6 1-10-1-29-20-48T68 73Q39 74 20 93T0 141q1 31 26 49q24 19 54 19q20 0 41-6q20-6 37-16q2-1 3-1q2 0 4 2t2 4q-4 20-35 142-30 122-36 144-1 3-1 6q0 6 6 11t21 5q23 0 30-6t9-15q13-57 89-396q75-338 86-386q1-5 12-46t14-55q0-1 1-2q0-1 0-2q0-7-4-9t-6-2Z'],
};

/** Bravura rest64th, SMuFL U+E4E9. */
export const bravuraRest64th: IconDefinition = {
  name: 'music:rest64th',
  viewBox: '-498.3 -548.3 1419.6 1419.6',
  paths: ['M414-423q-4 0-6 1-3 1-5 3-8 8-36 36-29 27-56 31q1-4 1-10-1-29-20-48t-48-20q-29 1-48 20t-20 48q2 32 27 50q25 19 55 19q20 0 39-7q19-6 37-15q2-1 4-1q1-1 3-1q4 0 6 3q3 3 3 8q0 4-2 10-3 11-18 75-16 64-21 81-7 15-26 27-20 12-34 13v-10q-1-29-20-48t-48-20q-29 1-48 20t-20 48q1 24 17 41t39 24q12 3 25 3q21 0 42-6q20-6 40-15q3-1 4-1q3 0 5 3q1 2 1 6q0 1 0 2q0 2-1 3-4 15-20 81-17 66-21 81-7 19-22 27t-27 8V137q-1-29-20-48T127 69Q98 70 79 89T59 137q0 16 8 29t20 22q13 9 28 14q6 2 13 3t14 1q11 0 21-2t19-5q10-4 15-7q6-4 15-8q2-1 3-1q4 0 5 5q1 4 1 9q0 2 0 5-1 2-1 3-3 12-19 77t-21 82q-6 16-20 23t-25 7q1-5 1-9-1-29-20-48T68 317q-29 1-48 20T0 385q0 15 8 28t20 22q11 9 26 13q14 5 28 5q15 0 33-5q18-4 31-11q3-1 4-1q5 0 7 5q1 4 1 8l-1 3q0 0 0 1L85 732q-1 4-1 7q0 7 7 10q8 4 25 4t24-4q7-5 9-13-2 9 21-81q22-90 109-462q2-5 11-43t13-56l93-400q1-5 12-46t15-56q0-8-3-11t-6-4Z'],
};

/** Bravura rest128th, SMuFL U+E4EA. */
export const bravuraRest128th: IconDefinition = {
  name: 'music:rest128th',
  viewBox: '-620.9 -832.9 1726.8 1726.8',
  paths: ['M373-621q-1-29-20-48t-48-20q-29 1-48 20t-20 48q0 15 8 28t20 22q11 9 26 13q14 5 28 5q11 0 21-2q11-2 20-5l1-1q10-3 17-6q8-4 17-8q2-1 4-1q2-1 4-1q5 0 8 3q4 3 4 10q0 3-1 8-5 21-19 80-15 60-20 77-5 13-26 28-22 16-38 17v-10q-1-29-20-48t-48-20q-29 1-48 20t-20 48q0 16 8 29t20 22q13 9 25 13t28 4q11 0 22-2q11-1 20-4q11-4 23-10q12-5 22-10q2-1 3-1q3 0 4 4t1 9q0 8-2 14L310-140q-5 16-24 27-18 12-32 13v-10q-1-29-20-48t-48-20q-29 1-48 20t-20 48q2 32 27 50q26 19 56 19q11 0 21-2t19-5q10-4 18-7q8-4 17-8q3-2 6-2q6 0 6 10q0 5-2 11-4 18-18 76-15 58-20 77-7 20-24 29t-29 9q0-2 1-5q0-2 0-5-1-29-20-48T128 69Q99 70 80 89T60 137q2 32 27 50q25 19 55 19q11 0 21-2t19-5q10-4 18-7q8-4 17-8q1-1 2-1t2 0q3 0 5 2q1 3 1 6-3 14-19 80-15 66-23 88-10 24-23 30-12 6-23 6l-3-10q-1-29-20-48T68 317q-29 1-48 20T0 385q2 32 27 50t55 18q11 0 21-2q11-2 20-5l1-1q10-3 18-6q8-4 17-8l1-1q6 0 6 5q0 1 0 2t-1 2q-6 23-37 148Q97 713 91 734q0 8 6 12t23 4q23 0 31-4q7-3 9-12L457-566q2-5 13-46q11-40 14-55q0-1 1-2q0-1 0-2q0-5-4-7-4-3-6-4-4 0-6 1-3 1-5 3-7 7-35 35-29 28-56 32Z'],
};

/** Bravura restDoubleWholeLegerLine, SMuFL U+E4F3. */
export const bravuraRestDoubleWholeLegerLine: IconDefinition = {
  name: 'music:restDoubleWholeLegerLine',
  viewBox: '-153 -419.5 600 600',
  paths: ['M284-219q5 0 7-3q3-3 3-7v-25q0-5-3-7-2-3-7-3H10q-4 0-7 3-3 2-3 7v25q0 4 3 7t7 3H85V-20H10q-4 0-7 3-3 2-3 7V15q0 4 3 7t7 3H284q5 0 7-3q3-3 3-7V-10q0-5-3-7-2-3-7-3H210V-219Z'],
};

/** Bravura restWholeLegerLine, SMuFL U+E4F4. */
export const bravuraRestWholeLegerLine: IconDefinition = {
  name: 'music:restWholeLegerLine',
  viewBox: '-168.6 -252.1 619.2 619.2',
  paths: ['M-99-20q-8 0-13 5t-5 13t5 13t13 5H0v93q0 11 7 18q8 8 19 8H256q11 0 18-8q8-7 8-18V17q-3-1 12-1q16 0 87 0q8 0 13-5t5-13-5-13-13-5Z'],
};

/** Bravura restHalfLegerLine, SMuFL U+E4F5. */
export const bravuraRestHalfLegerLine: IconDefinition = {
  name: 'music:restHalfLegerLine',
  viewBox: '-168.6 -374.1 619.2 619.2',
  paths: ['M381 13q8 0 13-5t5-13-5-13-13-5q-71 0-87 0-15 0-12-1v-92q0-11-8-18-7-8-18-8H26q-11 0-19 8-7 7-7 18v93H-99q-8 0-13 5t-5 13t5 13t13 5Z'],
};

/** Bravura accidentalDoubleFlat, SMuFL U+E264. */
export const bravuraAccidentalDoubleFlat: IconDefinition = {
  name: 'music:accidentalDoubleFlat',
  viewBox: '-161.6828 -498.2 734.4 734.4',
  paths: ['M314-151q-13 0-24 5-11 4-23 11-5 3-11 8t-13 5q-3 0-5-1-5-2-8-6-2-5-2-11q0-30 3-141q3-112 3-140q0-8-6-12-5-4-13-4-10 0-20 7-9 6-11 19q0 4 1 86t2 190q-22-16-51-16h-6q-14 0-25 5-10 4-22 11-6 3-12 8-5 5-12 5-1 0-2 0-2 0-3-1-5-2-8-6-3-5-3-11q0-30 4-141q3-112 3-140q0-8-6-12-5-4-13-4-11 0-20 7-10 6-11 19q0 35 3 287q4 252 9 294q5 5 9 5q2 0 4-1t2-1q23-13 43-30q19-18 36-31q28-20 49-39q21-20 35-38q1 57 3 94q2 38 4 41t4 4t4 1t4-1t2-1q23-13 42-30t36-30q67-48 95-91q28-44 27-79-1-43-28-68-26-25-63-26ZM67 93q-2 1-5 2-2 1-4 1-6 0-8-6-3-5-3-10q0-2-1-34-2-32-2-64q0-12 1-21q0-8 1-11q6-16 29-33q22-16 42-17q22 1 31 20t9 39q-1 42-28 77T67 93Zm184 0q-6 3-9 3-6 0-8-6-3-5-3-10q0-3-1-39-2-36-2-68q0-8 0-15q0-6 1-8q6-16 29-33q23-16 43-17q15 0 24 10q7 9 11 21q4 13 4 28-1 42-28 77-26 35-61 57Z'],
};

/** Bravura accidentalThreeQuarterTonesFlatZimmermann, SMuFL U+E281. */
export const bravuraAccidentalThreeQuarterTonesFlatZimmermann: IconDefinition = {
  name: 'music:accidentalThreeQuarterTonesFlatZimmermann',
  viewBox: '-134.9 -500.4 736.8 736.8',
  paths: ['M252 170q5 5 9 5q2 0 4-1t2-1q22-13 42-30q19-18 36-31q66-47 94-91q28-43 27-79-1-43-28-68t-62-27q-5 0-10 1-5 0-10 1-9 3-17 6-9 4-17 9-6 4-11 9-6 5-12 5-1 0-2 0-2 0-3-1-5-2-8-6-3-5-3-11l8-282q0-9-6-13-5-4-13-4-11 0-21 7t-11 21q0 35 3 287q3 251 9 294Zm-51 3q0 0 1 1q2 1 4 1t4-1q3-1 5-4q6-43 10-294q3-252 3-287-1-14-11-20-10-7-21-7-8 0-13 4-6 4-6 12l8 282q0 6-3 11-3 4-8 6-1 1-2 1-2 0-3 0-6 0-11-5-6-5-12-9-8-4-16-8-8-3-16-6l-1-1q-6-1-11-1-5-1-10-1-37 2-63 28Q2-100 1-58Q0-22 28 21q28 44 95 92q17 13 36 30t42 30ZM182-50q1 3 1 11q1 9 1 21q0 32-1 64-2 32-2 34q0 5-2 10-2 6-9 6-4 0-10-3-35-22-61-57Q72 0 71-42q0-14 4-27q4-12 11-20q11-11 26-11q6 0 12 2q7 1 14 5q12 7 26 19q14 13 18 24ZM287 80q0-2-1-34-2-32-2-64q0-12 1-21q0-8 1-11q6-17 29-33q22-16 42-17q22 1 31 20q8 18 8 38-1 44-27 78T307 93q-3 1-5 2t-4 1q-6 0-8-6-3-5-3-10Z'],
};

/** Bravura accidentalFlat, SMuFL U+E260. */
export const bravuraAccidentalFlat: IconDefinition = {
  name: 'music:accidentalFlat',
  viewBox: '-255.3828 -500.4 736.8 736.8',
  paths: ['M12 170q5 5 9 5q2 0 4-1t2-1q22-13 41-31q19-17 38-30q66-47 93-91q28-43 27-78-1-43-28-68-26-25-62-28-13 0-29 5-15 5-26 12-5 4-11 9-7 5-11 5-1 0-2 0-2 0-3-1-5-2-8-7t-3-10q1-30 4-142q3-111 3-140q0-8-6-13-5-4-13-4-11 0-20 7-10 7-11 21q0 35 3 287q3 251 9 294ZM47 81q0-3-1-35-2-33-2-65q0-12 1-21q0-8 1-11q7-16 29-32t41-17q22 1 31 20q10 18 10 38-2 41-28 78-27 36-61 57-6 3-10 3-7 0-9-6-2-5-2-9Z'],
};

/** Bravura accidentalQuarterToneFlatStein, SMuFL U+E280. */
export const bravuraAccidentalQuarterToneFlatStein: IconDefinition = {
  name: 'music:accidentalQuarterToneFlatStein',
  viewBox: '-254.4172 -500.4 736.8 736.8',
  paths: ['M215 170q6-43 9-294q3-252 3-287-1-14-11-21-9-7-20-7-8 0-13 4-6 5-6 13q0 29 3 140q3 112 4 142q0 5-3 10t-8 7q-1 1-2 1-2 0-3 0-4 0-11-5-6-5-11-9-11-7-26-12-16-5-29-5-36 3-62 27Q2-101 1-59Q0-23 28 21q27 44 93 91q19 13 38 30q19 18 41 31q0 0 2 1t4 1q5 0 9-5ZM180 81q0 4-2 9-2 6-9 6-4 0-10-3-34-21-61-57Q72-1 70-42q0-20 10-38q9-19 31-20q19 1 41 17t29 32q1 3 1 11q1 9 1 21q0 32-1 65-2 32-2 35Z'],
};

/** Bravura accidentalNatural, SMuFL U+E261. */
export const bravuraAccidentalNatural: IconDefinition = {
  name: 'music:accidentalNatural',
  viewBox: '-321.6 -408.6 811.2 811.2',
  paths: ['M141-181q-1 0-2 0-1 1-2 1-3 1-35 11-32 11-55 12-5 0-7-1-3-1-3-4V-329q0-5-4-9-3-3-8-3H12q-5 0-9 3-3 4-3 9V186q0 9 9 9l2-1q1 0 2 0t2-1q13-6 44-17q31-12 55-13q8 0 12 2q5 3 5 9V323q0 5 3 9q4 3 9 3h13q5 0 8-3q4-4 4-9V-179q0-4-2-6-3-2-6-2-1 0-2 0t-2 1ZM37-39q3-12 34-25q30-14 51-15q9-1 9 5V29q-3 14-32 27Q71 69 49 70q-5 0-9-2-3-1-3-4Z'],
};

/** Bravura accidentalQuarterToneSharpStein, SMuFL U+E282. */
export const bravuraAccidentalQuarterToneSharpStein: IconDefinition = {
  name: 'music:accidentalQuarterToneSharpStein',
  viewBox: '-306.5 -373 792 792',
  paths: ['M179-167q0-4-2-6-3-2-6-2-1 0-2 0t-2 1q-3 1-24 9-22 8-26 9-7 0-10-7-3-6-3-13V-296q0-5-4-8t-10-3q-11 0-14 5-3 6-3 12v130q0 6-2 14-3 7-8 12-13 5-26 11-12 6-25 11-5 2-8 6-4 5-4 10v71q0 9 9 9l2-1q3-1 22-9q18-8 27-11l1-1q5 0 9 5q4 6 4 12V79q0 8-3 14-2 6-7 8L12 123q-5 2-8 6-4 5-4 10v71q0 9 9 9l2-1q3-1 21-9q18-7 27-11q4-1 9 6q5 6 5 13V342q0 5 4 8t10 3q11 0 14-5q3-4 3-12V198q0-2 0-4t1-4q1-5 3-9q3-3 6-5q9-3 30-11q20-8 23-9q5-2 8-7q4-4 4-9V69q0-9-9-9l-2 1q0 0-1 0V60q-3 1-23 10-21 8-27 10-5 0-10-4-4-5-4-13V-30q0-7 4-16q3-10 9-13q9-4 29-12q20-7 22-8q5-2 8-7q4-5 4-10Z'],
};

/** Bravura accidentalSharp, SMuFL U+E262. */
export const bravuraAccidentalSharp: IconDefinition = {
  name: 'music:accidentalSharp',
  viewBox: '-294.3 -419.8 837.6 837.6',
  paths: ['M237-118q5-2 9-7q3-5 3-10v-71q0-4-2-6t-5-2q-1 0-2 0-2 0-3 1-1 0-11 4-9 4-14 5-5 0-10-4-4-3-4-9V-339q0-5-4-8t-10-3q-8 0-12 3t-4 8v130q-1 8-3 16-3 8-10 13-10 6-30 14-19 7-33 11-7-1-9-7-3-7-3-13V-295q0-5-4-8-5-3-10-3-8 0-12 3t-4 8v135q0 11-4 18-3 7-8 9-6 3-15 7-10 4-11 4-5 2-9 6-3 5-3 10v71q0 9 9 9l2-1q1 0 9-4q8-3 15-6l1-1q6 0 10 6t4 12V79q0 8-3 14-3 7-8 9-6 2-16 6t-11 5q-5 2-9 6-3 5-3 10v71q0 9 9 9l2-1q1 0 9-3t15-6q2-1 3-1q5 1 9 6q3 6 3 10V337q0 5 4 8t9 3q8 0 12-3q5-3 5-8V198q0-10 3-15q3-6 7-7l61-25q1 0 1 0l2-1q7 1 10 7q4 6 4 11V293q0 5 4 8t9 3q8 0 13-3q4-3 4-8V151q0-6 3-13t8-10q6-3 17-7q10-4 11-4q5-2 9-7q3-5 3-10V29q0-4-2-6t-5-2q-1 0-2 0-2 0-3 1L211 32q-5 0-9-5-4-4-4-13V-79q0-6 4-16q3-10 9-13ZM168 45q-7 16-32 27-25 12-44 13-5 0-8-1-3-2-4-4-1-4-2-18T77 30q0-24 1-46q1-21 2-28q4-14 28-25q24-12 45-13q5 0 9 1q4 2 6 5q2 4 3 20t1 37-1 39-3 25Z'],
};

/** Bravura accidentalThreeQuarterTonesSharpStein, SMuFL U+E283. */
export const bravuraAccidentalThreeQuarterTonesSharpStein: IconDefinition = {
  name: 'music:accidentalThreeQuarterTonesSharpStein',
  viewBox: '-269.6 -440.6 859.2 859.2',
  paths: ['M317-225q0-3-1-6-2-2-5-2-3 1-18 6t-20 7q-1 1-3 1t-3-2q-1-1-1-5V-353q0-10-3-13t-13-3-13 3-3 13v132q0 10-2 14t-6 5q-4 2-17 6-12 5-23 10-6 0-8-3-2-2-2-6V-322q0-10-3-13t-13-3-13 3-3 13v139q0 5-2 9-2 5-7 7L92-151q0 0-1 0l-1 1q-8 0-8-9V-292q0-10-3-13t-13-3-13 3-3 13v145q0 7-2 10-2 4-6 5L11-120q-4 1-6 3t-2 5v77q0 3 2 5q2 3 4 3q3 0 13-4q11-4 18-7q3-1 4-1q4 0 5 3q1 2 1 7V87q0 6-3 11-3 4-7 6L11 115q-4 1-6 3t-2 5v78q0 3 2 5q2 3 5 3q2 0 11-4q9-3 16-6q3-1 6-1q7 0 7 9V331q0 10 3 13t13 3t13-3t3-13V193q0-5 2-8q1-4 4-5l48-19q4 0 6 2t2 6V300q0 10 3 13t13 3t13-3t3-13V158q0-6 3-10q2-4 7-6l36-13q3-2 6-2q6 0 6 8V269q0 10 3 13t13 3t13-3t3-13V121q0-5 3-8t5-4l35-13q4-1 6-3t2-5V10q0-2-1-5-2-3-5-3-3 1-16 5-12 5-19 8l-1 1q-4 0-7-3-2-4-2-9V-113q0-5 1-8q1-4 5-5q5-2 20-7q15-6 17-7q8-2 8-8ZM234 31q-4 7-20 14-17 8-29 9-4 0-6-2-1-3-2-22-1-18-1-43q0-27 1-50q1-22 2-27q5-7 23-15q18-7 29-8q1 0 2 0q1 1 1 1q2 3 2 19q1 17 1 39q0 29-1 54q0 26-2 31ZM82 88q-2-4-3-19q0-15 0-36q0-29 1-55q1-25 2-32q4-7 24-16q21-8 33-9q2 0 3 1q1 0 2 1q2 3 2 20q1 18 1 42q0 27-1 51q0 23-2 29-4 8-23 16-20 8-33 9-4 0-6-2Z'],
};

/** Bravura accidentalDoubleSharp, SMuFL U+E263. */
export const bravuraAccidentalDoubleSharp: IconDefinition = {
  name: 'music:accidentalDoubleSharp',
  viewBox: '-176.4444 -301.05 600 600',
  paths: ['M190 32q-10-5-28-16Q145 5 143-1q2-11 18-20q17-10 29-14q2 0 3 0l6 1q10 0 21-2q12-2 20-8q4-4 5-14q2-10 2-22q1-30-7-39-7-9-37-8-14 0-25 2-12 1-16 5-3 3-4 14t-1 25q-4 10-14 28-10 17-19 19-11-2-21-18Q93-69 90-81q0-13-2-24-2-12-6-15-3-4-13-5-11-2-23-2-13 0-25 2-11 1-16 5-2 2-4 12Q0-97 0-83T1-58Q3-47 5-44q6 5 17 7q12 3 25 3q3 0 5-1q3 0 5 0q10 5 28 16Q102-8 104-2Q102 8 86 18T58 32H48q-14 0-26 2-12 1-17 5-2 3-4 13Q0 63 0 77t1 25q2 11 4 13q6 5 16 7q11 3 24 3q12 0 22-2q10-3 15-8q4-4 6-15t2-23q0-1 1-2q0-1 1-2q5-12 13-26q8-15 18-16q10 2 20 18t14 28q0 14 1 25q1 10 4 13q6 5 16 7q11 3 24 3q28 0 37-10t8-36q0-13-2-25-2-11-5-15-4-4-15-5-12-2-25-2Z'],
};

/** Bravura gClef, SMuFL U+E050. */
export const bravuraGClef: IconDefinition = {
  name: 'music:gClef',
  viewBox: '-718.2286 -1273.6214 2107.4571 2107.4571',
  paths: ['M376-415q-1-9 0-12q2-3 6-7q83-76 136-171q52-95 54-210q0-66-17-127-17-60-48-106-12-18-27-33-16-16-25-17-11 1-30 16t-35 32q-55 63-77 147T292-739q0 44 4 88q5 44 10 76q2 8 1 13-1 4-10 11Q184-463 95-350Q5-237 0-87Q0 48 90 148q90 99 274 104q18 0 36-2q18-1 33-4q8-2 11-1t4 10q10 52 18 108t9 93q-4 107-57 138T316 622q-40-1-60-10t-20-19q0-5 7-9q8-3 25-8q25-6 45-29q21-22 22-65q0-42-25-72-25-29-71-30-51 1-79 34t-28 81q-2 53 38 106q41 53 152 57q56 3 124-36q67-40 73-164-1-45-10-105-10-60-19-109-2-8 1-11q2-2 12-6q77-31 122-92T671-11q-1-99-65-169-64-69-176-72-19 1-23-2-5-3-6-16Zm94-528q25 0 42 20q17 21 18 62-3 83-57 151-54 67-117 119-5 5-8 3-4-1-5-11-3-20-4-44-2-24-2-48q3-118 44-185q41-66 89-67ZM361-262q3 13 0 17-2 3-15 7-67 24-105 76-39 53-40 118q1 68 32 114q31 45 83 63q6 2 14 4q7 2 13 2t9-3t3-8-5-8q-4-3-10-5-32-14-52-43-19-29-20-64q1-43 27-74q27-30 73-43q12-3 15-2q4 2 5 10l50 298q2 8-1 10-2 2-13 4-12 2-26 4-15 1-30 1-133-2-210-66Q82 86 80-20Q78-64 95-123q18-58 78-129q45-49 81-82q37-32 72-60q7-6 10-5t4 9Zm69 159q-2-9 0-12t11-2q62 7 104 51q42 45 44 112-1 48-26 84-25 37-68 58-9 5-12 4t-4-10Z'],
};

/** Bravura fClef, SMuFL U+E062. */
export const bravuraFClef: IconDefinition = {
  name: 'music:fClef',
  viewBox: '-198.7 -351.7 1076.4 1076.4',
  paths: ['M252-262q-130 5-191 75Q-1-116 0-39Q0 23 31 65q31 43 92 45q48-1 77-30q28-29 29-76-1-49-30-76-28-28-66-28-20 0-30 3-11 4-20 4-10 0-13-5t-3-13q1-33 43-72q42-38 119-41q79 2 116 72q36 70 36 189-1 206-98 339Q186 508 10 605q-7 4-11 8t-4 10q0 5 3 8q3 4 10 4q8 0 17-5q193-88 345-232T531 28q-1-132-75-210-73-78-204-80Zm377 82q-24 1-39 16t-16 39q1 24 16 39t39 16q24-1 39-16t16-39q-1-24-16-39t-39-16Zm1 251q-24 0-39 15t-15 39t15 39t39 15t39-15t15-39-15-39-39-15Z'],
};

/** Bravura cClef, SMuFL U+E05C. */
export const bravuraCClef: IconDefinition = {
  name: 'music:cClef',
  viewBox: '-257.6914 -607.2 1214.4 1214.4',
  paths: ['M230-482q0-21-21-21h-1q-21 0-21 21V482q0 21 21 21h1q21 0 21-21V44q0-6 3-6q3-1 6 0q21 3 46 33q26 30 43 113q2 12 7 18q5 7 12 7q8 0 13-7q4-7 8-20q9-35 32-63t75-30q48 0 66 48q18 49 17 147q1 98-22 144t-84 46q-14 0-48-6-33-6-37-21q1-4 9-8q9-4 18-7q16-5 28-21q11-16 12-44-1-33-19-51-19-18-49-18-33 0-55 21-21 21-22 61q0 49 42 87q43 37 132 39q122-4 180-71q57-66 56-148-1-105-55-169-54-63-154-65-22 0-36 3-15 3-25 6-8 2-15 3-7 0-14-4-11-8-23-26-12-19-13-35q1-16 13-35q12-18 23-26q7-4 14-4q7 1 15 3q10 3 25 6q14 3 36 3q100-2 154-65q54-64 55-169q1-82-56-149-58-66-180-70-89 2-132 39-42 38-42 87q1 40 22 61q22 21 55 21q30 0 49-18q18-18 19-51-1-28-12-44-12-16-28-21-9-3-18-7-8-4-9-8q4-15 37-21q34-6 48-6q61 0 84 46t22 144q1 98-17 147-18 48-66 48-52-2-75-30t-32-63q-4-13-8-20-5-7-13-7-7 0-12 6-5 7-7 19-17 83-43 113-25 30-46 33-3 1-6 0-3 0-3-6ZM21-503Q0-503 0-482V482q0 21 21 21h86q21 0 21-21V-482q0-21-21-21Z'],
};

/** Bravura articAccentAbove, SMuFL U+E4A0. */
export const bravuraArticAccentAbove: IconDefinition = {
  name: 'music:articAccentAbove',
  viewBox: '-130.5 -423 600 600',
  paths: ['M326-105q9-2 11-7t2-11-2-11q-2-4-11-7L26-243q-3-1-6-1-2-1-3-1-7 0-10 4T2-231T0-221t3 7q3 4 11 7q13 4 109 37t117 40q4 1 5 3q2 2 2 4t-2 4-6 3q-21 7-117 39Q27-44 14-40Q6-36 3-33q-3 4-3 8t2 9Q4-10 8-6q3 5 8 5q1 0 2 0t2-1Z'],
};

/** Bravura articAccentBelow, SMuFL U+E4A1. */
export const bravuraArticAccentBelow: IconDefinition = {
  name: 'music:articAccentBelow',
  viewBox: '-130.5 -178 600 600',
  paths: ['M326 140q9-2 11-7t2-11-2-11q-2-4-11-7L26 2q-3-1-6-1-2-1-3-1Q10 0 7 4T2 14T0 24t3 7q3 4 11 7q13 4 109 37t117 40q4 1 5 3q2 2 2 4t-2 4-6 3q-21 7-117 39-95 33-108 37-8 4-11 7-3 4-3 8t2 9q2 6 6 10q3 5 8 5q1 0 2 0t2-1Z'],
};

/** Bravura articStaccatoAbove, SMuFL U+E4A2. */
export const bravuraArticStaccatoAbove: IconDefinition = {
  name: 'music:articStaccatoAbove',
  viewBox: '-258 -342 600 600',
  paths: ['M84-42q0-18-12-30T42-84T12-72T0-42T12-12T42 0T72-12T84-42Z'],
};

/** Bravura articStaccatoBelow, SMuFL U+E4A3. */
export const bravuraArticStaccatoBelow: IconDefinition = {
  name: 'music:articStaccatoBelow',
  viewBox: '-258 -258 600 600',
  paths: ['M84 42q0-18-12-30T42 0T12 12T0 42T12 72T42 84T72 72T84 42Z'],
};

/** Bravura articTenutoAbove, SMuFL U+E4A4. */
export const bravuraArticTenutoAbove: IconDefinition = {
  name: 'music:articTenutoAbove',
  viewBox: '-131.5 -324 600 600',
  paths: ['M314 0q17 0 21-7t3-17q1-10-3-17t-21-7H23Q6-48 2-41T-1-24Q-2-14 2-7T23 0Z'],
};

/** Bravura articTenutoBelow, SMuFL U+E4A5. */
export const bravuraArticTenutoBelow: IconDefinition = {
  name: 'music:articTenutoBelow',
  viewBox: '-131.5 -276 600 600',
  paths: ['M314 48q17 0 21-7t3-17q1-10-3-17T314 0H23Q6 0 2 7T-1 24Q-2 34 2 41t21 7Z'],
};

/** Bravura articStaccatissimoAbove, SMuFL U+E4A6. */
export const bravuraArticStaccatissimoAbove: IconDefinition = {
  name: 'music:articStaccatissimoAbove',
  viewBox: '-249.5 -445.5 600 600',
  paths: ['M50-293q-20 0-34 6T1-271q1 27 16 142T50 2Q70-13 84-125q15-113 16-145-1-11-15-17t-35-6Z'],
};

/** Bravura articStaccatissimoBelow, SMuFL U+E4A7. */
export const bravuraArticStaccatissimoBelow: IconDefinition = {
  name: 'music:articStaccatissimoBelow',
  viewBox: '-249.5 -152.5 600 600',
  paths: ['M50 295q21 0 35-6t15-17q-1-32-16-145Q70 15 50 0Q32 16 17 131T1 273q1 10 15 16t34 6Z'],
};

/** Bravura articMarcatoAbove, SMuFL U+E4AC. */
export const bravuraArticMarcatoAbove: IconDefinition = {
  name: 'music:articMarcatoAbove',
  viewBox: '-183 -426 600 600',
  paths: ['M126-247q-4-6-10-6-5 0-8 3-2 3-2 3L0-16q-1 1-1 2q0 2 0 3q0 4 2 7Q2-1 6 0Q7 1 9 1q1 0 2 0q3 0 6-2q3-1 5-5q3-7 27-60t29-63q1-3 4-3t6 3q4 10 29 63T145-6q5 6 11 6h68q11-2 11-11q0-3-1-5Z'],
};

/** Bravura articMarcatoBelow, SMuFL U+E4AD. */
export const bravuraArticMarcatoBelow: IconDefinition = {
  name: 'music:articMarcatoBelow',
  viewBox: '-183 -173 600 600',
  paths: ['M108 248q4 6 10 6q5 0 8-3q2-3 2-3L234 17q1-1 1-3q0-1 0-2q0-4-2-7-1-3-5-4-1-1-2-1-2 0-3 0-3 0-6 2-3 1-5 5-3 7-27 60t-29 63q-1 3-4 3t-6-3q-4-10-29-63T89 7Q84 1 78 1H10Q-1 3-1 12q0 3 1 5Z'],
};

/** Bravura fermataAbove, SMuFL U+E4C0. */
export const bravuraFermataAbove: IconDefinition = {
  name: 'music:fermataAbove',
  viewBox: '-57.2 -524.9105 722.4 722.4',
  paths: ['M302-221q155 9 209 84T568-25q1 2 1 4t1 3q5 10 9 16q5 5 12 5t10-3q4-4 4-11q0-4-1-10-57-220-162-269-106-48-138-39-34-9-139 39Q60-241 4-21Q3-15 3-10Q3-3 7 0q3 3 9 3q7 0 11-5q5-6 9-16q1-1 2-3q0-3 1-6q5-39 59-112q54-74 204-82ZM358-52q-1-22-16-38-16-15-39-16-22 1-38 16-15 16-16 38q1 23 16 39Q281 2 303 3q23-1 39-16q15-16 16-39Z'],
};

/** Bravura fermataBelow, SMuFL U+E4C1. */
export const bravuraFermataBelow: IconDefinition = {
  name: 'music:fermataBelow',
  viewBox: '-57.2 -194.4895 722.4 722.4',
  paths: ['M302 224q-150-8-204-82Q44 69 39 30q-1-3-1-6-1-2-2-3-4-11-9-16-4-5-11-5-6 0-9 3Q3 6 3 13q0 5 1 11Q60 244 165 293q105 48 139 39q32 9 138-39Q547 244 604 24q1-6 1-10q0-7-4-11-3-3-10-3T579 5q-4 5-9 16-1 1-1 3t-1 4q-3 37-57 112T302 224ZM358 55q-1-23-16-39Q326 1 303 0q-22 1-38 16-15 16-16 39q1 22 16 38q16 15 38 16q23-1 39-16q15-16 16-38Z'],
};

/** Bravura ornamentTrill, SMuFL U+E566. */
export const bravuraOrnamentTrill: IconDefinition = {
  name: 'music:ornamentTrill',
  viewBox: '-52.1 -502.6 625.2 625.2',
  paths: ['M266-390q-3 0-7 1t-6 2l-49 16q-7 2-10 5-4 4-7 11l-36 88q-3 7-4 10-2 2-4 2-3 0-8-3-4-3-11-6-10-5-21-7-10-2-21-2-36 0-59 19Q1-235 0-203q0 24 16 40t50 17q9 0 18-1q8-1 13-1q3 0 3 3t-3 10L86-108Q78-88 72-72q-5 16-5 32Q67-19 81-5Q96 9 124 10q41 0 71-30t31-86q0-18-3-35t-10-33q-1-4-2-6t-1-4q0-4 5-9q5-4 17-11l6-3q26-16 45-25q19-10 33-10q7 0 10 3t3 12q0 8-2 16t-4 13L250-17q-3 7-3 11q0 6 11 6h49q7 0 10-2q3-3 6-10l65-162q11-26 30-47q20-22 37-23q10 0 10 6-1 6-11 13t-11 27q0 15 10 23q10 9 26 9q18 0 30-14q12-15 12-41q0-22-12-37t-40-16q-20 0-35 9-16 9-27 22-6 7-9 11-2 3-5 3t-3-5q-1-6-6-17-5-10-16-16t-28-6q-30 1-57 11-26 11-42 20-10 5-15 8t-9 3q-3 0-3-3t2-7q1-4 3-8l50-124q3-7 3-11q0-6-6-6ZM82-250q10 0 30 6q19 7 21 18q0 2-1 6-1 3-3 7l-4 10q-3 9-8 13t-14 6q-20 5-35 5-24-1-33-10t-8-20q0-14 13-27q12-13 42-14Zm107 83q7 3 10 28q4 24 4 34-1 34-17 58-16 25-39 26-6 0-8-3-3-4-3-9q0-6 3-15q2-8 5-16-1 2 5-13q7-15 34-83q1-4 3-5q1-2 3-2Z'],
};

/** Bravura ornamentTurn, SMuFL U+E567. */
export const bravuraOrnamentTurn: IconDefinition = {
  name: 'music:ornamentTurn',
  viewBox: '-70 -409 600 600',
  paths: ['M371-218q-24 0-40 11-15 11-16 33q0 17 10 26q10 10 26 10q20-1 29-12q8-10 22-11q13 0 23 14q10 13 10 33-1 32-19 48-19 16-46 16-24 0-50-20-26-19-58-55-36-41-73-66t-85-26q-50 1-77 33T0-103Q2-49 28-25Q55 0 89 0q24 0 40-11q15-11 16-33q0-17-10-26-10-10-26-10-20 1-28 11-9 11-23 12-13-1-23-14T25-104q1-32 19-48q19-16 46-16q24 0 50 19q26 20 58 56q36 41 73 66T356-1q50-1 77-33t27-81q-2-54-28-79-27-24-61-24Z'],
};

/** Bravura ornamentTurnInverted, SMuFL U+E568. */
export const bravuraOrnamentTurnInverted: IconDefinition = {
  name: 'music:ornamentTurnInverted',
  viewBox: '-73 -409 600 600',
  paths: ['M86-218q-34 0-61 24-26 25-28 79q0 49 27 81T101-1q48-1 85-26t73-66q32-36 58-56q26-19 50-19q27 0 46 16q18 16 19 48q0 20-10 33T399-57q-14-1-22-12-9-10-29-11-16 0-26 10-10 9-10 26q1 22 16 33Q344 0 368 0q34 0 61-25q26-24 28-78q0-49-27-81t-77-33q-48 1-85 26t-73 66q-32 36-58 55-26 20-50 20-27 0-46-16-18-16-19-48q0-20 10-33q10-14 23-14q14 1 23 11q8 11 28 12q16 0 26-10q10-9 10-26-1-22-16-33-16-11-40-11Z'],
};

/** Bravura ornamentShortTrill, SMuFL U+E56C. */
export const bravuraOrnamentShortTrill: IconDefinition = {
  name: 'music:ornamentShortTrill',
  viewBox: '-72.5 -557.5 870 870',
  paths: ['M298-116L209-226q-5-7-11-12-7-5-20-7-5 0-10 2t-12 7q-35 38-71 79-36 42-74 84-4 4-7 10-4 6-4 13q0 5 4 7q5 3 16 3q7 0 14-3T49-53l61-54q5-4 11-4q4 0 7 3q4 3 9 9q7 8 42 44q34 36 44 48q3 4 9 5q5 2 11 2t11-1q5-2 8-4l108-98q5-5 9-7q4-1 6-1q4 0 7 3q3 2 9 9q8 8 42 44T488-7q3 4 9 5q5 2 11 2t11-1q5-2 8-4q15-15 90-96t94-103q5-6 9-13q5-7 5-10-1-8-10-13t-17-5q-9 0-18 7-12 12-45 53-34 41-46 54-12 10-19 10-5 0-9-3t-8-7q-10-11-42-50-32-38-43-49-6-6-12-10t-11-4q-7 0-12 1-5 2-12 7-7 6-12 12-6 7-11 13-21 23-43 47t-47 48q-5 6-10 0Z'],
};

/** Bravura ornamentMordent, SMuFL U+E56D. */
export const bravuraOrnamentMordent: IconDefinition = {
  name: 'music:ornamentMordent',
  viewBox: '-71.8 -559.8 873.6 873.6',
  paths: ['M379-184V-319H348v169l-29 34q-3 4-7 4t-7-4q-29-34-59-69-30-34-36-42-6-6-12-12-7-5-19-6-7 0-11 2-5 2-11 7L14-74Q9-69 5-63Q1-56 1-51t4 7q5 3 16 3q12-1 22-8q10-8 18-16q10-8 19-17q10-9 20-17q7-6 13-10q5-3 9-3t7 3q4 3 8 9L224-7q3 4 9 5q5 2 11 2q5 0 10-2q5-1 8-4q10-7 40-34q29-26 44-39V73h32V-106q6-5 12-5q4 0 8 2q4 3 8 9q7 9 42 45q34 36 45 48q3 4 8 5q6 2 11 2q13 0 19-6q16-15 90-96q75-81 94-103l2-3q5-5 8-10q4-5 4-10-1-8-10-12-9-5-16-5-10 0-18 7-12 11-46 52-33 41-46 54-6 5-10 8-4 2-8 2-5 0-10-3-4-3-8-7-10-11-41-49-32-39-43-50-7-6-13-10t-12-4-11 2q-4 2-11 7t-12 12q-6 7-11 13Z'],
};

/** Bravura noteheadSlashHorizontalEnds, SMuFL U+E101. */
export const bravuraNoteheadSlashHorizontalEnds: IconDefinition = {
  name: 'music:noteheadSlashHorizontalEnds',
  viewBox: '-53 -318 636 636',
  paths: ['M430-250L0 250H100L530-250Z'],
};

/** Bravura noteheadSlashWhiteWhole, SMuFL U+E102. */
export const bravuraNoteheadSlashWhiteWhole: IconDefinition = {
  name: 'music:noteheadSlashWhiteWhole',
  viewBox: '-98 -588 1176 1176',
  paths: ['M430-250L0 250H550L980-250Zm415 30L475 220H125L495-220Z'],
};

/** Bravura noteheadSlashWhiteHalf, SMuFL U+E103. */
export const bravuraNoteheadSlashWhiteHalf: IconDefinition = {
  name: 'music:noteheadSlashWhiteHalf',
  viewBox: '-78 -468 936 936',
  paths: ['M430-250L0 250H350L780-250Zm215 30L275 220H125L495-220Z'],
};

/** Bravura noteheadSlashWhiteDoubleWhole, SMuFL U+E10A. */
export const bravuraNoteheadSlashWhiteDoubleWhole: IconDefinition = {
  name: 'music:noteheadSlashWhiteDoubleWhole',
  viewBox: '-116.1 -696.6 1393.2 1393.2',
  paths: ['M521-250L91 250H641l430-500ZM9-250q-4 0-7 2-2 3-2 6V243q0 6 9 7H22q4 0 6-2q3-2 3-5V-242q0-3-3-6-2-2-6-2Zm58 0q-5 0-7 2-3 3-3 6V243q0 3 3 5q2 2 7 2H79q4 0 7-2t3-5V-242q0-3-3-6-3-2-7-2Zm1014 0q-4 0-7 2-2 3-2 6V243q0 6 9 7h13q4 0 6-2q3-2 3-5V-242q0-3-3-6-2-2-6-2Zm58 0q-5 0-7 2-3 3-3 6V243q0 3 3 5q2 2 7 2h12q4 0 7-2t3-5V-242q0-3-3-6-3-2-7-2ZM936-220L566 220H216L586-220Z'],
};

/** Bravura noteheadBlack, SMuFL U+E0A4. */
export const bravuraNoteheadBlack: IconDefinition = {
  name: 'music:noteheadBlack',
  viewBox: '-152.5 -300 600 600',
  paths: ['M97 125q71-2 132-52q62-49 66-115-1-39-27-61-27-22-70-22-85 2-140 51Q2-25 0 42q1 39 28 61q28 22 69 22Z'],
};

/** Bravura augmentationDot, SMuFL U+E1E7. */
export const bravuraAugmentationDot: IconDefinition = {
  name: 'music:augmentationDot',
  viewBox: '-250 -300 600 600',
  paths: ['M100 0q0-22-14-36T50-50Q29-50 15-36T0 0Q1 21 15 35T50 50q22-1 36-15T100 0Z'],
};

/** Bravura dynamicForte, SMuFL U+E522. */
export const bravuraDynamicForte: IconDefinition = {
  name: 'music:dynamicForte',
  viewBox: '-246.0762 -503.6 715.2 715.2',
  paths: ['M16-264Q0-264 0-248q0 15 15 15H73q4 0 6 0q2 1 2 4t-2 10L16 0Q-4 72-22 102q-19 29-48 28-10 0-14-3-4-2-4-6q0-5 6-6q7 0 18-7q9-6 15-16q5-9 5-21q0-20-12-30-12-11-33-11-23 1-37 16-15 15-15 39q1 33 22 50t53 17q56 0 97-40T112-12q21-45 39-95t36-113l1-1q0-3 5-7q4-5 8-5h65q16 0 16-16q0-15-15-15H207q-5 0-8-1-2 0-2-4q0-2 1-5q0-3 1-7q14-66 35-103q20-36 57-37q6 0 11 2t5 6-4 5q-4 2-12 5-10 5-15 14-6 10-6 24q0 21 13 31q13 11 32 11q20 0 34-13t15-41-19-47-67-20q-72 1-116 46-44 46-68 119-3 11-7 13-3 2-13 2Z'],
};

/** Bravura barlineSingle, SMuFL U+E030. */
export const bravuraBarlineSingle: IconDefinition = {
  name: 'music:barlineSingle',
  viewBox: '-582 -1100 1200 1200',
  paths: ['M36 0V-1000H0V0Z'],
};

/** Bravura tuplet3, SMuFL U+E883. */
export const bravuraTuplet3: IconDefinition = {
  name: 'music:tuplet3',
  viewBox: '-142 -483.5 600 600',
  paths: ['M122-207q-10 0-15 4t-5 11t5 11t15 4h10q28 0 41 15q14 15 14 39q0 35-23 69T95-18q-15 0-25-5-11-5-11-13q0-4 4-7q3-2 9-5q9-4 17-14q7-10 8-29q0-18-11-27t-27-9q-21 1-35 17T10-69q0 31 25 53Q60 7 113 8q65-1 109-35q44-35 46-95q0-19-10-36-9-16-29-26-5-2-8-4-3-1-3-5q0-2 3-4t9-5q32-13 54-36q21-23 22-53-1-39-33-62-31-22-78-22-48 0-81 23T78-288q0 20 10 31q10 12 28 12q19 0 32-13t13-34q0-8-3-14-2-7-6-11-5-4-9-8-3-3-3-5q0-5 9-10q8-4 24-4q29 1 41 15q11 14 11 31q0 40-24 65t-68 26Z'],
};
